services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
