services:
  redis:
    image: redis:7-alpine
    command: redis-server --replica-read-only no --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - internal-network
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /app/node_modules
    environment:
      - PORT=${PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    depends_on:
      - redis
    networks:
      - internal-network
  worker:
    build: .
    command: npm run start:worker
    environment:
      - PORT=${PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    volumes:
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - internal-network
networks:
  internal-network:
    driver: bridge
